<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cz.bliksoft.java</groupId>
		<artifactId>dependency-management</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>dependency-management-slf4j</artifactId>
	<packaging>pom</packaging>

	<dependencies>
		<!--
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-reload4j</artifactId>
		</dependency>
		-->

		<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-nop -->
		<!-- <dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-nop</artifactId>
		</dependency> -->

		<!--
		https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j18-impl -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j18-impl</artifactId>
		</dependency>

	</dependencies>
</project>